export const USERINFO = {
  UPDATEUSERINFO: 'UPDATEUSERINFO',
  GATEUSERINFO: 'GATEUSERINFO',
  UPDATEUSERTOKEN: 'UPDATEUSERTOKEN'
};

export const TESTUSER = {
  GETUSERINFO: 'GETUSERINFO'
};

export const SETTINGS = {
  UPDATELANGUAGE: 'UPDATELANGUAGE',
  UPDATETHEME: 'UPDATETHEME',
  UPDATESCREEN: 'UPDATESCREEN',
  UPDATESETTINGS: 'UPDATESETTINGS',
  UPDATENETWORKCONNECTIVITY: 'UPDATENETWORKCONNECTIVITY',
  UPDATENETISCONNECTED: 'UPDATENETISCONNECTED',
  UPDATEHAPTICFEEDBACK: 'UPDATEHAPTICFEEDBACK',
  UPDATECCFFNTUPPERDISPHAPTIC:'UPDATECCFFNTUPPERDISPHAPTIC'

};

